############################################################################
# 原則 http://jekyllrb.com/docs/configuration/#default-configuration からの
# 差分のみ記述している。記述順序も前述に従う。

### Handling Reading
# デフォルトと同じだが「utf-8で記事を書こう」という宣言的な意味合で残した。
encoding: utf-8

### Filtering Content
future: true

### Outputting
# デフォルトと同じだが、万が一デフォルトが変わってしまうと記事のURLが変わってし
# まいクリティカルなので、明示的に指定した。
permalink: date

### Markdown Processors
kramdown:
  input: GFM

############################################################################
# 以下はvim-jp固有の設定項目

# baseurl と紛らわしいが別物なので要注意
base-url:    http://vim-jp.org/vimdoc-en
