name: Generate vim help
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '36 20 * * Sat'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          path: work
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          path: target
          ref: gh-pages
      - name: Setup Vim
        uses: thinca/action-setup-vim@v1
        with:
          vim_version: 'v8.2.0020'
          vim_type: 'Vim'
      - name: Generate new document
        run: |
          cd work
          # Create tags
          make html

          cd ..
          # install
          cp work/target/html/doc/*.html target
      - name: Commit updated master branch
        uses: EndBug/add-and-commit@v7
        with:
          cwd: './target'
          author_name: '${{ github.actor }}'
          author_email: '${{ github.actor }}@users.noreply.github.com'
          message: 'Generated by GitHub workflow ${{ github.run_id }}'
          branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.VIMDOC_JP_TOKEN }}
