name: Generate vim help
on:
  push:
    branches:
      - master
  schedule:
    - cron: '5 12 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initialization
        run: |
          sudo apt-get update
          # libfuse2 and LD_PRELOAD are needed for appimage.
          sudo apt-get -y install libfuse2
          echo "LD_PRELOAD=/lib/x86_64-linux-gnu/libgmodule-2.0.so" >> $GITHUB_ENV
      - name: checkout master
        uses: actions/checkout@v4
        with:
          path: work
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          path: target
          ref: gh-pages
      - name: Setup Vim
        uses: thinca/action-setup-vim@v2
        with:
          vim_version: 'v9.1.0065'
          vim_type: 'Vim'
      - name: Generate new document
        run: |
          cd work
          # Create html documents
          make html

          cd ..
          # install
          cp work/target/html/doc/*.html target
      - name: Check commit IDs
        id: commitid
        run: |
          echo "vim=$(git -C work/vim rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "vim_faq=$(git -C work/vim_faq rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Commit updated gh-pages branch
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './target'
          default_author: github_actions
          message: |-
            Generated by GitHub workflow ${{ github.run_id }}

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Used commits:
            https://github.com/vim/vim/commit/${{ steps.commitid.outputs.vim }}
            https://github.com/chrisbra/vim_faq/commit/${{ steps.commitid.outputs.vim_faq }}
